Generate all schedules (#73)
* Add WeekSchedule class/modified repr of TimeBlock

* Declared required functions for schedule genration

* Implemented all schedule generation functions

* Comment schedule functions for readability/clarity

* Added import copy

* Added test cases for schedule gen + dataclass tags

* Update dataclass notation and migrate to Pytest for consistency with backend

* Update Github Action to run tests on the Scraper pre-merge

* Remove redundant file paths checker for GH merge action

* Add black formatter to SSH scraper

* Format Files

---------

Co-authored-by: Jeremy Sanchez <jeremy,sanchez1@upr.edu>
Co-authored-by: Poggecci <alejandro.cruzado@upr.edu>

diff --git a/.github/workflows/scraper-merge-checks.yml b/.github/workflows/scraper-merge-checks.yml
--- a/.github/workflows/scraper-merge-checks.yml
+++ b/.github/workflows/scraper-merge-checks.yml
@@ -1,4 +1,4 @@
-name: Backend Pre-Merge Checks
+name: SSH Scraper Pre-Merge Checks
 
 on:
   pull_request:
@@ -6,7 +6,7 @@ on:
       - main
       - develop
     paths:
-      - 'backend/**'
+      - 'ssh-scraper/**'
 
 jobs:
   format-and-test:
@@ -47,24 +47,25 @@ jobs:
           export PATH="$HOME/.poetry/bin:$PATH"
         shell: bash
 
-      - name: Install Backend Dependencies with Poetry
-        working-directory: backend/ # Navigate to the backend folder
+      - name: Install SSH-Scraper Dependencies with Poetry
+        working-directory: ssh-scraper/ # Navigate to the scraper folder
         run: poetry install
-
-      - name: Check Backend Code Formatting with Black
-        working-directory: backend/ # Navigate to the backend folder
+    
+      - name: Check Scraper Code Formatting with Black
+        working-directory: ssh-scraper/ # Navigate to the scraper folder
         run: |
-          poetry run black --check .  # Check for code formatting issues
-          if [ $? -ne 0 ]; then
-              echo "Error: Unformatted files found, run 'poetry run black .' from backend/ ."
-              exit 1
-          fi
+            poetry run black --check .  # Check for code formatting issues
+            if [ $? -ne 0 ]; then
+                echo "Error: Unformatted files found, run 'poetry run black .' from backend/ ."
+                exit 1
+            fi
 
-      - name: Run Backend Tests with Pytest
-        working-directory: backend/ # Navigate to the backend folder
+      - name: Run Scraper Tests with Pytest
+        working-directory: ssh-scraper/ # Navigate to the scraper folder
         run: |
-          poetry run pytest 
-          if [ $? -ne 0 ]; then
-              echo "Error: Some tests failed when running Pytest."
-              exit 1
-          fi
+            poetry run pytest 
+            if [ $? -ne 0 ]; then
+                echo "Error: Some tests failed when running Pytest."
+                exit 1
+            fi
+                
